# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [ ]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]

def same(arr):
    return arr[0] == arr[-1]
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True
print(same(numbers_x))
print(same(numbers_y))
# numbers_y = [75, 65, 35, 75, 30]
# result is False





# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [2]:
#code here
import numpy as np
x1  = np.array([[10, 20, 30, 40, 10],[75, 65, 35, 75, 30]])
x2 = np.array([[10, 20, 30, 40, 10],[10, 20, 30, 40, 10]])
print(x1 + x2)
print(x1 * x2)

[[ 20  40  60  80  20]
 [ 85  85  65 115  40]]
[[ 100  400  900 1600  100]
 [ 750 1300 1050 3000  300]]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [6]:
#code here
import random
x = np.random.randint(0,10,12)
x = x.reshape(3,4)
x

array([[3, 4, 5, 5],
       [6, 7, 4, 5],
       [8, 2, 1, 2]])

# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [2]:
#Code here
shopping_cart = []
print("Welcome to the store!")
print("Available Products are: ")
print("1. Milk")
print("2. Bread")
print("3. Eggs")
products = {'Milk': 0, 'Bread': 0, 'Eggs': 0}
user_input = input('Enter your choice here:')
while user_input.lower() != 'q':
    if user_input == '1':
        print('Purchased Milk!')
        products['Milk'] += 1
    elif user_input == '2':
        print('Purchased Bread!')
        products['Bread'] += 1
    elif user_input == '3':
        print('Purchased Eggs!')
        products['Eggs'] += 1
    else:
        print('Invalid input!')
    user_input = input('Enter your choice here:')
print('Thanks for shopping with us!')
print('You have purchased:')
for key, value in products.items():
    if value > 0:
        print(key, value)

Welcome to the store!
Available Products are: 
1. Milk
2. Bread
3. Eggs
Purchased Bread!
Purchased Milk!
Purchased Eggs!
Thanks for shopping with us!
You have purchased:
Milk 1
Bread 1
Eggs 1


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [4]:
#code here

promotional_words = ['buy', 'discount', 'sale', 'shop', 'offer','promo']
spam_words = ['nigerian', 'prince', 'inheritance', 'money', 'rich', 'wealthy', 'savings']
important_words = ['meeting', 'project', 'deadline', 'client', 'team', 'email', 'send', 'attachment']

def classify_emails(emails):
    important_emails = []
    spam_emails = []
    promotional_emails = []
    for email in emails:
        email = email.lower()
        if any(word in email for word in important_words):
            important_emails.append(email)
        elif any(word in email for word in spam_words):
            spam_emails.append(email)
        elif any(word in email for word in promotional_words):
            promotional_emails.append(email)
    return important_emails, spam_emails, promotional_emails

emails = ['Hello, I am a Nigerian prince and I have an inheritance for you', 'Meeting at 10am tomorrow', 'Buy 1 get 1 free', 'Project deadline approaching, send the email with the attachment']
print(classify_emails(emails))

(['meeting at 10am tomorrow', 'project deadline approaching, send the email with the attachment'], ['hello, i am a nigerian prince and i have an inheritance for you'], ['buy 1 get 1 free'])


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [2]:
#code here
import PyDictionary as pD
dictionary = pD.PyDictionary()
word = input('Enter a word: ')
word = word.lower()
while word.lower() != 'q':
    if dictionary.meaning(word) is not None:
        print(dictionary.translate(word, 'es'))
    else:
        print('Word not found!')   
    word = input('Enter a word: ')

Invalid Word
None
Invalid Word
None




# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [6]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv', index_col=0)

In [7]:
total_global_sales = df['Global_Sales'].sum()
print(total_global_sales)

8920.44


In [10]:
highest_global_sales = df['Global_Sales'].max()
df[df['Global_Sales'] == highest_global_sales]

Name Platform    Year   Genre Publisher  NA_Sales  EU_Sales  \
Rank                                                                      
1     Wii Sports      Wii  2006.0  Sports  Nintendo     41.49     29.02   

      JP_Sales  Other_Sales  Global_Sales  
Rank                                       
1         3.77         8.46         82.74

In [11]:
avg_NA_Sales = df['NA_Sales'].mean()
avg_EU_Sales = df['EU_Sales'].mean()
avg_JP_Sales = df['JP_Sales'].mean()
avg_Other_Sales = df['Other_Sales'].mean()
print(avg_NA_Sales, avg_EU_Sales, avg_JP_Sales, avg_Other_Sales)

0.26466742981082064 0.14665200626581515 0.077781660441017 0.0480630196409206


In [12]:
df.nlargest(5, 'Global_Sales')

Name Platform    Year         Genre Publisher  \
Rank                                                                      
1                   Wii Sports      Wii  2006.0        Sports  Nintendo   
2            Super Mario Bros.      NES  1985.0      Platform  Nintendo   
3               Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
4            Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
5     Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

      NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
Rank                                                           
1        41.49     29.02      3.77         8.46         82.74  
2        29.08      3.58      6.81         0.77         40.24  
3        15.85     12.88      3.79         3.31         35.82  
4        15.75     11.01      3.28         2.96         33.00  
5        11.27      8.89     10.22         1.00         31.37

In [20]:
total_sales = df.groupby('Genre').sum()

In [24]:
NA_sales = df.groupby('Genre')['NA_Sales'].sum()
NA_sales

Genre
Action          877.83
Adventure       105.80
Fighting        223.59
Misc            410.24
Platform        447.05
Puzzle          123.78
Racing          359.42
Role-Playing    327.28
Shooter         582.60
Simulation      183.31
Sports          683.35
Strategy         68.70
Name: NA_Sales, dtype: float64

In [25]:
df.tail(10)

Name Platform    Year  \
Rank                                                                        
16591                                   Mega Brain Boost       DS  2008.0   
16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV  2016.0   
16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP  2007.0   
16594                                Myst IV: Revelation       PC  2004.0   
16595                                           Plushees       DS  2008.0   
16596                 Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                      Men in Black II: Alien Escape       GC  2003.0   
16598   SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                         Know How 2       DS  2010.0   
16600                                   Spirits & Spells      GBA  2003.0   

              Genre              Publisher  NA_Sales  EU_Sales  JP_Sales  \
Rank                                                                       
16591        Puzzle  Majesco Entertainment      0.01      0.00      0.00   
16592        Action        dramatic create      0.00      0.00      0.01   
16593  Role-Playing     Falcom Corporation      0.00      0.00      0.01   
16594     Adventure                Ubisoft      0.01      0.00      0.00   
16595    Simulation              Destineer      0.01      0.00      0.00   
16596      Platform                  Kemco      0.01      0.00      0.00   
16597       Shooter             Infogrames      0.01      0.00      0.00   
16598        Racing             Activision      0.00      0.00      0.00   
16599        Puzzle               7G//AMES      0.00      0.01      0.00   
16600      Platform                Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  Total_Sales  
Rank                                           
16591          0.0          0.01         0.01  
16592          0.0          0.01         0.01  
16593          0.0          0.01         0.01  
16594          0.0          0.01         0.01  
16595          0.0          0.01         0.01  
16596          0.0          0.01         0.01  
16597          0.0          0.01         0.01  
16598          0.0          0.01         0.00  
16599          0.0          0.01         0.01  
16600          0.0          0.01         0.01

In [30]:
most_popular_platform = df['Platform'].value_counts()
most_popular_platform[0:3]

Platform
DS     2163
PS2    2161
PS3    1329
Name: count, dtype: int64

In [32]:
df['NA_Percentage'] = (df['NA_Sales'] / df['Global_Sales']) * 100
df['EU_Percentage'] = (df['EU_Sales'] / df['Global_Sales']) * 100
df['JP_Percentage'] = (df['JP_Sales'] / df['Global_Sales']) * 100
df['Other_Percentage'] = (df['Other_Sales'] / df['Global_Sales']) * 100
df

Name Platform    Year  \
Rank                                                                       
1                                            Wii Sports      Wii  2006.0   
2                                     Super Mario Bros.      NES  1985.0   
3                                        Mario Kart Wii      Wii  2008.0   
4                                     Wii Sports Resort      Wii  2009.0   
5                              Pokemon Red/Pokemon Blue       GB  1996.0   
...                                                 ...      ...     ...   
16596                Woody Woodpecker in Crazy Castle 5      GBA  2002.0   
16597                     Men in Black II: Alien Escape       GC  2003.0   
16598  SCORE International Baja 1000: The Official Game      PS2  2008.0   
16599                                        Know How 2       DS  2010.0   
16600                                  Spirits & Spells      GBA  2003.0   

              Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  Other_Sales  \
Rank                                                                         
1            Sports    Nintendo     41.49     29.02      3.77         8.46   
2          Platform    Nintendo     29.08      3.58      6.81         0.77   
3            Racing    Nintendo     15.85     12.88      3.79         3.31   
4            Sports    Nintendo     15.75     11.01      3.28         2.96   
5      Role-Playing    Nintendo     11.27      8.89     10.22         1.00   
...             ...         ...       ...       ...       ...          ...   
16596      Platform       Kemco      0.01      0.00      0.00         0.00   
16597       Shooter  Infogrames      0.01      0.00      0.00         0.00   
16598        Racing  Activision      0.00      0.00      0.00         0.00   
16599        Puzzle    7G//AMES      0.00      0.01      0.00         0.00   
16600      Platform     Wanadoo      0.01      0.00      0.00         0.00   

       Global_Sales  Total_Sales  NA_Percentage  EU_Percentage  JP_Percentage  \
Rank                                                                            
1             82.74        82.74      50.145033      35.073725       4.556442   
2             40.24        40.24      72.266402       8.896620      16.923459   
3             35.82        35.83      44.249023      35.957566      10.580681   
4             33.00        33.00      47.727273      33.363636       9.939394   
5             31.37        31.38      35.926044      28.339178      32.578897   
...             ...          ...            ...            ...            ...   
16596          0.01         0.01     100.000000       0.000000       0.000000   
16597          0.01         0.01     100.000000       0.000000       0.000000   
16598          0.01         0.00       0.000000       0.000000       0.000000   
16599          0.01         0.01       0.000000     100.000000       0.000000   
16600          0.01         0.01     100.000000       0.000000       0.000000   

       Other_Percentage  
Rank                     
1             10.224801  
2              1.913519  
3              9.240648  
4              8.969697  
5              3.187759  
...                 ...  
16596          0.000000  
16597          0.000000  
16598          0.000000  
16599          0.000000  
16600          0.000000  

[16598 rows x 15 columns]

In [35]:
df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].corr()

NA_Sales  EU_Sales  JP_Sales  Other_Sales
NA_Sales     1.000000  0.767727  0.449787     0.634737
EU_Sales     0.767727  1.000000  0.435584     0.726385
JP_Sales     0.449787  0.435584  1.000000     0.290186
Other_Sales  0.634737  0.726385  0.290186     1.000000